id: P3C43E3C0
initial_creation_type: input
source_metadata:
  title: Tsongkhapa Lobzang Drakpa Series
  language: pt
  description: 'Texts by and about the great master Tsongkhapa Lobzang Drakpa (tsong
    kha pa blo bzang grags pa) (1357–1419), founder of the Gelug school:'
  volume:
    23830e9fb35c4ce3a6e2e4890d1cd2fd:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    89458942866a4bfd9a1c2518ee84c211:
      title: Short Guru Yoga of the Noble Lord, All-Knowing Tsongkhapa
      parent: Guru Yoga
    7b0915654796448b8e01b014d6d170b2:
      title: Three Principal Aspects of the Path
      parent: Mind Training
    ff3316c1cb4c4e4fa5e136d582a7df04:
      title: Praise to Mañjughoṣa
      parent: Praise
    3edfa264f5304dccba9f7238e27b0128:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Praise
    c8f3003372e64f3db99923f90e4ede80:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    60ffa8bc14ac407ea1d58c0152985381:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
    f8209d60bf434950bc726de69acf799a:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T01:55:51.975487'
last_modified_at: '2022-03-01T01:55:51.975489'
